import type { LanguageCode } from "./types";
import { uiText as baseUiText, uiFormat as baseUiFormat } from "./localizedUi";

type SecondaryLanguage = Exclude<LanguageCode, "pt" | "en">;
type Variables = Record<string, string | number>;

const extra: Record<SecondaryLanguage, Record<string, string>> = {
  fr: {
    "Operation under control": "Opération sous contrôle",
    "workers on site": "travailleurs sur chantier",
    "Find talent": "Rechercher des talents",
    "Manage teams": "Gérer les équipes",
    "Active projects": "Chantiers actifs",
    "total": "au total",
    "Teams": "Équipes",
    "professionals": "professionnels",
    "On site now": "Sur chantier maintenant",
    "Active attendance": "Présences actives",
    "Contracts": "Contrats",
    "Available to view": "Consultables",
    "Team monitoring": "Suivi de l’équipe",
    "Active check-ins and operational status": "Entrées actives et état opérationnel",
    "View all attendance": "Voir toutes les présences",
    "View all": "Voir tout",
    "No active attendance right now.": "Aucune présence active pour le moment.",
    "Project pulse": "Suivi des chantiers",
    "Progress across key sites": "Progression des principaux chantiers",
    "Manage projects": "Gérer les chantiers",
    "Manage": "Gérer",
    "Recorded hours": "Heures enregistrées",
    "Recent demo records": "Derniers relevés de démonstration",
    "Valid and viewable": "Valides et consultables",
    "Professional portfolio": "Portfolio professionnel",
    "Available in records": "Disponibles dans les archives",
    "Current project": "Chantier actuel",
    "Work session active": "Session de travail active",
    "Ready to check in": "Prêt à enregistrer l’arrivée",
    "Schedule": "Horaires",
    "Expected end": "Fin prévue",
    "Location": "Localisation",
    "No project has been assigned yet.": "Aucun chantier n’a encore été attribué.",
    "Next shift": "Prochain poste",
    "Daily planning": "Planning quotidien",
    "View schedule": "Voir les horaires",
    "No assigned project": "Aucun chantier attribué",
    "Check-in available near the site.": "L’enregistrement d’arrivée est disponible à proximité du chantier.",
    "View attendance": "Voir les présences",
    "Top skills": "Compétences principales",
    "Validated professional development": "Évolution professionnelle validée",
    "Edit skills": "Modifier les compétences",
    "On site": "Sur chantier",
    "WORKER PULSE": "ACTIVITÉ TRAVAILLEUR",
    "Control centre for check-ins, check-outs and site GPS zones.": "Centre de contrôle des entrées, sorties et zones GPS des chantiers.",
    "Show all": "Tout afficher",
    "Active only": "Actifs uniquement",
    "Active sessions": "Sessions actives",
    "Inside geofence": "Dans la zone GPS",
    "Radius set per site": "Rayon défini par chantier",
    "Completed records": "Enregistrements terminés",
    "Location source": "Source de localisation",
    "Configurable operational geofence per site.": "Zone GPS opérationnelle configurable par chantier.",
    "No records for this filter": "Aucun enregistrement pour ce filtre",
    "Location-protected check-in, schedule and attendance history.": "Enregistrement d’arrivée protégé par localisation, horaires et historique des présences.",
    "Active session": "Session active",
    "Ready to validate site zone": "Prêt à valider la zone du chantier",
    "Since": "Depuis",
    "GPS obtained · distance unavailable": "GPS obtenu · distance indisponible",
    "GPS validated · {distance} m from site centre": "GPS validé · {distance} m du centre du chantier",
    "Outside zone · {distance} m from site centre": "Hors zone · {distance} m du centre du chantier",
    "Demo mode · no real GPS validation": "Mode démonstration · aucune validation GPS réelle",
    "Authorised zone: {radius} m radius": "Zone autorisée : rayon de {radius} m",
    "Validate GPS and check in": "Valider le GPS et enregistrer l’arrivée",
    "GPS check-in is accepted only within {radius} m of the site centre. If GPS is unavailable, the demo continues clearly marked as DEMO.": "L’enregistrement GPS est accepté uniquement à moins de {radius} m du centre du chantier. Si le GPS est indisponible, la démonstration reste clairement indiquée comme DÉMO.",
    "Attendance history": "Historique des présences",
    "records": "enregistrements",
    "No records yet": "Aucun enregistrement pour le moment",
    "In": "Entrée",
    "Out": "Sortie",
    "Complete": "Terminé",
    "Duration": "Durée",
    "Check-in blocked: you are {distance} m from the site. Move within {radius} m.": "Arrivée bloquée : vous êtes à {distance} m du chantier. Rapprochez-vous à moins de {radius} m.",
    "Create teams, choose leaders and allocate workers.": "Créez des équipes, choisissez les responsables et affectez les travailleurs.",
    "New team": "Nouvelle équipe",
    "No teams yet": "Aucune équipe pour le moment",
    "Create the first team and add workers.": "Créez la première équipe et ajoutez des travailleurs.",
    "Create team": "Créer une équipe",
    "Edit team": "Modifier l’équipe",
    "Team operational settings": "Configuration opérationnelle de l’équipe",
    "Delete team?": "Supprimer l’équipe ?",
    "The team will be removed from assigned projects. Worker profiles will not be deleted.": "L’équipe sera retirée des chantiers attribués. Les profils des travailleurs ne seront pas supprimés.",
    "Assigned": "Attribuée",
    "Available": "Disponible",
    "No project assigned": "Aucun chantier attribué",
    "members": "membres",
    "Trust": "Confiance",
    "Team name": "Nom de l’équipe",
    "E.g. South Structure Team": "Ex. : Équipe Structure Sud",
    "Specialty": "Spécialité",
    "Description": "Description",
    "Inactive": "Inactive",
    "No project": "Aucun chantier",
    "Assigned project": "Chantier attribué",
    "Assign the leader or remove members.": "Désignez le responsable ou retirez des membres.",
    "Team has no members": "L’équipe ne compte aucun membre",
    "Add workers": "Ajouter des travailleurs",
    "Profiles available in the WORKLY network.": "Profils disponibles dans le réseau WORKLY.",
    "About": "À propos",
    "Phone": "Téléphone",
    "Country": "Pays",
    "Age": "Âge",
    "Professional indicators": "Indicateurs professionnels",
    "Overall rating": "Évaluation globale",
    "Skills": "Compétences",
    "Editable levels in your profile.": "Niveaux modifiables dans votre profil.",
    "Edit Worker profile": "Modifier le profil Travailleur",
    "Changes are stored in this demo.": "Les modifications sont enregistrées dans cette démonstration.",
    "Name": "Nom",
    "Trade": "Métier",
    "Professional bio": "Biographie professionnelle",
    "Skills — one per line: Name:Level": "Compétences — une par ligne : Nom:Niveau",
    "Company": "Entreprise",
    "Tax ID": "N° fiscal",
    "Operational capacity": "Capacité opérationnelle",
    "Projects": "Chantiers",
    "Documents": "Documents",
    "Edit Company profile": "Modifier le profil Entreprise",
    "Company name": "Nom de l’entreprise",
    "Industry": "Secteur",
    "Profile updated.": "Profil mis à jour.",
    "Company updated.": "Entreprise mise à jour.",
    "Team created.": "Équipe créée.",
    "Team updated.": "Équipe mise à jour.",
    "Team deleted.": "Équipe supprimée.",
    "Worker added.": "Travailleur ajouté.",
    "Worker removed.": "Travailleur retiré.",
    "Leader assigned.": "Responsable désigné.",
    "Project created.": "Chantier créé.",
    "Project updated.": "Chantier mis à jour.",
    "Project deleted.": "Chantier supprimé.",
    "Assignment completed.": "Affectation terminée.",
    "Check-in saved in demo mode because the network is unavailable.": "Arrivée enregistrée en mode démonstration car le réseau est indisponible.",
    "Check-in recorded.": "Arrivée enregistrée.",
    "Check-out recorded.": "Sortie enregistrée.",
    "Demo data reset.": "Données de démonstration réinitialisées.",
    "WORKER": "TRAVAILLEUR",
    "COMPANY": "ENTREPRISE"
  },
  es: {
    "Operation under control": "Operación bajo control", "workers on site": "trabajadores en obra", "Find talent": "Buscar talento", "Manage teams": "Gestionar equipos", "Active projects": "Obras activas", total: "en total", Teams: "Equipos", professionals: "profesionales", "On site now": "En obra ahora", "Active attendance": "Presencias activas", Contracts: "Contratos", "Available to view": "Consultables", "Team monitoring": "Monitorización del equipo", "Active check-ins and operational status": "Entradas activas y estado operativo", "View all attendance": "Ver toda la asistencia", "View all": "Ver todo", "No active attendance right now.": "No hay presencias activas en este momento.", "Project pulse": "Pulso de las obras", "Progress across key sites": "Progreso de las obras principales", "Manage projects": "Gestionar obras", Manage: "Gestionar", "Recorded hours": "Horas registradas", "Recent demo records": "Últimos registros demo", "Valid and viewable": "Válidos y consultables", "Professional portfolio": "Portafolio profesional", "Available in records": "Disponibles en el archivo", "Current project": "Obra actual", "Work session active": "Sesión de trabajo activa", "Ready to check in": "Listo para registrar entrada", Schedule: "Horario", "Expected end": "Fin previsto", Location: "Ubicación", "No project has been assigned yet.": "Todavía no hay ninguna obra asignada.", "Next shift": "Próximo turno", "Daily planning": "Planificación diaria", "View schedule": "Ver horario", "No assigned project": "Sin obra asignada", "Check-in available near the site.": "El registro de entrada está disponible cerca de la obra.", "View attendance": "Ver asistencia", "Top skills": "Competencias destacadas", "Validated professional development": "Evolución profesional validada", "Edit skills": "Editar competencias", "On site": "En obra", "WORKER PULSE": "PULSO DEL TRABAJADOR",
    "Control centre for check-ins, check-outs and site GPS zones.": "Centro de control de entradas, salidas y zonas GPS de las obras.", "Show all": "Mostrar todos", "Active only": "Solo activos", "Active sessions": "Sesiones activas", "Inside geofence": "Dentro de la geocerca", "Radius set per site": "Radio definido por obra", "Completed records": "Registros completados", "Location source": "Origen de la ubicación", "Configurable operational geofence per site.": "Geocerca operativa configurable por obra.", "No records for this filter": "No hay registros para este filtro", "Location-protected check-in, schedule and attendance history.": "Registro de entrada protegido por ubicación, horario e historial de asistencia.", "Active session": "Sesión activa", "Ready to validate site zone": "Listo para validar la zona de la obra", Since: "Desde", "GPS obtained · distance unavailable": "GPS obtenido · distancia no disponible", "GPS validated · {distance} m from site centre": "GPS validado · {distance} m del centro de la obra", "Outside zone · {distance} m from site centre": "Fuera de la zona · {distance} m del centro de la obra", "Demo mode · no real GPS validation": "Modo demo · sin validación GPS real", "Authorised zone: {radius} m radius": "Zona autorizada: radio de {radius} m", "Validate GPS and check in": "Validar GPS y registrar entrada", "GPS check-in is accepted only within {radius} m of the site centre. If GPS is unavailable, the demo continues clearly marked as DEMO.": "El registro GPS solo se acepta a menos de {radius} m del centro de la obra. Si el GPS no está disponible, la demostración continúa claramente marcada como DEMO.", "Attendance history": "Historial de asistencia", records: "registros", "No records yet": "Aún no hay registros", In: "Entrada", Out: "Salida", Complete: "Completado", Duration: "Duración", "Check-in blocked: you are {distance} m from the site. Move within {radius} m.": "Entrada bloqueada: estás a {distance} m de la obra. Acércate hasta {radius} m.",
    "Create teams, choose leaders and allocate workers.": "Crea equipos, elige responsables y distribuye trabajadores.", "New team": "Nuevo equipo", "No teams yet": "Aún no hay equipos", "Create the first team and add workers.": "Crea el primer equipo y añade trabajadores.", "Create team": "Crear equipo", "Edit team": "Editar equipo", "Team operational settings": "Configuración operativa del equipo", "Delete team?": "¿Eliminar equipo?", "The team will be removed from assigned projects. Worker profiles will not be deleted.": "El equipo se eliminará de las obras asignadas. Los perfiles de los trabajadores no se eliminarán.", Assigned: "Asignado", Available: "Disponible", "No project assigned": "Sin obra asignada", members: "miembros", Trust: "Confianza", "Team name": "Nombre del equipo", "E.g. South Structure Team": "Ej.: Equipo Estructura Sur", Specialty: "Especialidad", Description: "Descripción", Inactive: "Inactivo", "No project": "Sin obra", "Assigned project": "Obra asignada", "Assign the leader or remove members.": "Define al responsable o elimina miembros.", "Team has no members": "El equipo no tiene miembros", "Add workers": "Añadir trabajadores", "Profiles available in the WORKLY network.": "Perfiles disponibles en la red WORKLY.",
    About: "Sobre", Phone: "Teléfono", Country: "País", Age: "Edad", "Professional indicators": "Indicadores profesionales", "Overall rating": "Valoración general", Skills: "Competencias", "Editable levels in your profile.": "Niveles editables en tu perfil.", "Edit Worker profile": "Editar perfil de Trabajador", "Changes are stored in this demo.": "Los cambios se guardan en esta demostración.", Name: "Nombre", Trade: "Profesión", "Professional bio": "Biografía profesional", "Skills — one per line: Name:Level": "Competencias — una por línea: Nombre:Nivel", Company: "Empresa", "Tax ID": "NIF", "Operational capacity": "Capacidad operativa", Projects: "Obras", Documents: "Documentos", "Edit Company profile": "Editar perfil de Empresa", "Company name": "Nombre de la empresa", Industry: "Sector",
    "Profile updated.": "Perfil actualizado.", "Company updated.": "Empresa actualizada.", "Team created.": "Equipo creado.", "Team updated.": "Equipo actualizado.", "Team deleted.": "Equipo eliminado.", "Worker added.": "Trabajador añadido.", "Worker removed.": "Trabajador eliminado.", "Leader assigned.": "Responsable asignado.", "Project created.": "Obra creada.", "Project updated.": "Obra actualizada.", "Project deleted.": "Obra eliminada.", "Assignment completed.": "Asignación completada.", "Check-in saved in demo mode because the network is unavailable.": "Entrada guardada en modo demo porque la red no está disponible.", "Check-in recorded.": "Entrada registrada.", "Check-out recorded.": "Salida registrada.", "Demo data reset.": "Datos demo restablecidos.", WORKER: "TRABAJADOR", COMPANY: "EMPRESA"
  },
  ro: {
    "Operation under control": "Operațiune sub control", "workers on site": "lucrători pe șantier", "Find talent": "Caută profesioniști", "Manage teams": "Gestionează echipele", "Active projects": "Șantiere active", total: "în total", Teams: "Echipe", professionals: "profesioniști", "On site now": "Pe șantier acum", "Active attendance": "Prezențe active", Contracts: "Contracte", "Available to view": "Disponibile pentru consultare", "Team monitoring": "Monitorizarea echipei", "Active check-ins and operational status": "Intrări active și stare operațională", "View all attendance": "Vezi toate prezențele", "View all": "Vezi tot", "No active attendance right now.": "Nu există prezențe active în acest moment.", "Project pulse": "Starea șantierelor", "Progress across key sites": "Progresul principalelor șantiere", "Manage projects": "Gestionează șantierele", Manage: "Gestionează", "Recorded hours": "Ore înregistrate", "Recent demo records": "Ultimele înregistrări demo", "Valid and viewable": "Valabile și disponibile", "Professional portfolio": "Portofoliu profesional", "Available in records": "Disponibile în arhivă", "Current project": "Șantier curent", "Work session active": "Sesiune de lucru activă", "Ready to check in": "Pregătit pentru intrare", Schedule: "Program", "Expected end": "Finalizare estimată", Location: "Locație", "No project has been assigned yet.": "Nu a fost atribuit încă niciun șantier.", "Next shift": "Următoarea tură", "Daily planning": "Planificare zilnică", "View schedule": "Vezi programul", "No assigned project": "Niciun șantier atribuit", "Check-in available near the site.": "Intrarea este disponibilă în apropierea șantierului.", "View attendance": "Vezi prezența", "Top skills": "Competențe principale", "Validated professional development": "Dezvoltare profesională validată", "Edit skills": "Editează competențele", "On site": "Pe șantier", "WORKER PULSE": "ACTIVITATE LUCRĂTOR",
    "Control centre for check-ins, check-outs and site GPS zones.": "Centru de control pentru intrări, ieșiri și zone GPS ale șantierelor.", "Show all": "Afișează toate", "Active only": "Doar active", "Active sessions": "Sesiuni active", "Inside geofence": "În zona GPS", "Radius set per site": "Rază stabilită pe șantier", "Completed records": "Înregistrări finalizate", "Location source": "Sursa locației", "Configurable operational geofence per site.": "Zonă GPS operațională configurabilă pentru fiecare șantier.", "No records for this filter": "Nicio înregistrare pentru acest filtru", "Location-protected check-in, schedule and attendance history.": "Intrare protejată prin locație, program și istoricul prezenței.", "Active session": "Sesiune activă", "Ready to validate site zone": "Pregătit pentru validarea zonei șantierului", Since: "Din", "GPS obtained · distance unavailable": "GPS obținut · distanță indisponibilă", "GPS validated · {distance} m from site centre": "GPS validat · {distance} m de centrul șantierului", "Outside zone · {distance} m from site centre": "În afara zonei · {distance} m de centrul șantierului", "Demo mode · no real GPS validation": "Mod demo · fără validare GPS reală", "Authorised zone: {radius} m radius": "Zonă autorizată: rază de {radius} m", "Validate GPS and check in": "Validează GPS și înregistrează intrarea", "GPS check-in is accepted only within {radius} m of the site centre. If GPS is unavailable, the demo continues clearly marked as DEMO.": "Intrarea GPS este acceptată doar la maximum {radius} m de centrul șantierului. Dacă GPS-ul nu este disponibil, demonstrația rămâne marcată clar ca DEMO.", "Attendance history": "Istoricul prezenței", records: "înregistrări", "No records yet": "Nu există încă înregistrări", In: "Intrare", Out: "Ieșire", Complete: "Finalizat", Duration: "Durată", "Check-in blocked: you are {distance} m from the site. Move within {radius} m.": "Intrare blocată: ești la {distance} m de șantier. Apropie-te la maximum {radius} m.",
    "Create teams, choose leaders and allocate workers.": "Creează echipe, alege lideri și repartizează lucrători.", "New team": "Echipă nouă", "No teams yet": "Nu există încă echipe", "Create the first team and add workers.": "Creează prima echipă și adaugă lucrători.", "Create team": "Creează echipă", "Edit team": "Editează echipa", "Team operational settings": "Configurarea operațională a echipei", "Delete team?": "Ștergi echipa?", "The team will be removed from assigned projects. Worker profiles will not be deleted.": "Echipa va fi eliminată de pe șantierele atribuite. Profilurile lucrătorilor nu vor fi șterse.", Assigned: "Atribuită", Available: "Disponibilă", "No project assigned": "Niciun șantier atribuit", members: "membri", Trust: "Încredere", "Team name": "Numele echipei", "E.g. South Structure Team": "Ex.: Echipa Structură Sud", Specialty: "Specialitate", Description: "Descriere", Inactive: "Inactivă", "No project": "Niciun șantier", "Assigned project": "Șantier atribuit", "Assign the leader or remove members.": "Stabilește liderul sau elimină membri.", "Team has no members": "Echipa nu are membri", "Add workers": "Adaugă lucrători", "Profiles available in the WORKLY network.": "Profiluri disponibile în rețeaua WORKLY.",
    About: "Despre", Phone: "Telefon", Country: "Țară", Age: "Vârstă", "Professional indicators": "Indicatori profesionali", "Overall rating": "Evaluare generală", Skills: "Competențe", "Editable levels in your profile.": "Niveluri editabile în profilul tău.", "Edit Worker profile": "Editează profilul Lucrător", "Changes are stored in this demo.": "Modificările sunt salvate în această demonstrație.", Name: "Nume", Trade: "Meserie", "Professional bio": "Biografie profesională", "Skills — one per line: Name:Level": "Competențe — una pe linie: Nume:Nivel", Company: "Companie", "Tax ID": "Cod fiscal", "Operational capacity": "Capacitate operațională", Projects: "Șantiere", Documents: "Documente", "Edit Company profile": "Editează profilul Companie", "Company name": "Numele companiei", Industry: "Sector",
    "Profile updated.": "Profil actualizat.", "Company updated.": "Companie actualizată.", "Team created.": "Echipă creată.", "Team updated.": "Echipă actualizată.", "Team deleted.": "Echipă ștearsă.", "Worker added.": "Lucrător adăugat.", "Worker removed.": "Lucrător eliminat.", "Leader assigned.": "Lider stabilit.", "Project created.": "Șantier creat.", "Project updated.": "Șantier actualizat.", "Project deleted.": "Șantier șters.", "Assignment completed.": "Atribuire finalizată.", "Check-in saved in demo mode because the network is unavailable.": "Intrare salvată în mod demo deoarece rețeaua nu este disponibilă.", "Check-in recorded.": "Intrare înregistrată.", "Check-out recorded.": "Ieșire înregistrată.", "Demo data reset.": "Date demo resetate.", WORKER: "LUCRĂTOR", COMPANY: "COMPANIE"
  },
  de: {
    "Operation under control": "Betrieb unter Kontrolle", "workers on site": "Mitarbeiter auf Baustelle", "Find talent": "Fachkräfte suchen", "Manage teams": "Teams verwalten", "Active projects": "Aktive Baustellen", total: "insgesamt", Teams: "Teams", professionals: "Fachkräfte", "On site now": "Jetzt auf Baustelle", "Active attendance": "Aktive Anwesenheiten", Contracts: "Verträge", "Available to view": "Einsehbar", "Team monitoring": "Teamüberwachung", "Active check-ins and operational status": "Aktive Check-ins und Betriebsstatus", "View all attendance": "Alle Anwesenheiten anzeigen", "View all": "Alle anzeigen", "No active attendance right now.": "Derzeit keine aktive Anwesenheit.", "Project pulse": "Baustellenstatus", "Progress across key sites": "Fortschritt der wichtigsten Baustellen", "Manage projects": "Baustellen verwalten", Manage: "Verwalten", "Recorded hours": "Erfasste Stunden", "Recent demo records": "Letzte Demo-Einträge", "Valid and viewable": "Gültig und einsehbar", "Professional portfolio": "Berufsportfolio", "Available in records": "Im Archiv verfügbar", "Current project": "Aktuelle Baustelle", "Work session active": "Aktive Arbeitssitzung", "Ready to check in": "Bereit zum Einchecken", Schedule: "Arbeitszeit", "Expected end": "Voraussichtliches Ende", Location: "Standort", "No project has been assigned yet.": "Noch keine Baustelle zugewiesen.", "Next shift": "Nächste Schicht", "Daily planning": "Tagesplanung", "View schedule": "Arbeitszeit anzeigen", "No assigned project": "Keine Baustelle zugewiesen", "Check-in available near the site.": "Check-in in der Nähe der Baustelle verfügbar.", "View attendance": "Anwesenheit anzeigen", "Top skills": "Top-Kompetenzen", "Validated professional development": "Validierte berufliche Entwicklung", "Edit skills": "Kompetenzen bearbeiten", "On site": "Auf Baustelle", "WORKER PULSE": "MITARBEITERSTATUS",
    "Control centre for check-ins, check-outs and site GPS zones.": "Kontrollzentrum für Check-ins, Check-outs und GPS-Zonen der Baustellen.", "Show all": "Alle anzeigen", "Active only": "Nur aktive", "Active sessions": "Aktive Sitzungen", "Inside geofence": "Innerhalb der GPS-Zone", "Radius set per site": "Radius je Baustelle", "Completed records": "Abgeschlossene Einträge", "Location source": "Standortquelle", "Configurable operational geofence per site.": "Konfigurierbare operative GPS-Zone je Baustelle.", "No records for this filter": "Keine Einträge für diesen Filter", "Location-protected check-in, schedule and attendance history.": "Standortgeschützter Check-in, Arbeitszeit und Anwesenheitsverlauf.", "Active session": "Aktive Sitzung", "Ready to validate site zone": "Bereit zur Prüfung der Baustellenzone", Since: "Seit", "GPS obtained · distance unavailable": "GPS erfasst · Entfernung nicht verfügbar", "GPS validated · {distance} m from site centre": "GPS validiert · {distance} m vom Baustellenzentrum", "Outside zone · {distance} m from site centre": "Außerhalb der Zone · {distance} m vom Baustellenzentrum", "Demo mode · no real GPS validation": "Demo-Modus · keine echte GPS-Prüfung", "Authorised zone: {radius} m radius": "Zulässige Zone: {radius} m Radius", "Validate GPS and check in": "GPS prüfen und einchecken", "GPS check-in is accepted only within {radius} m of the site centre. If GPS is unavailable, the demo continues clearly marked as DEMO.": "GPS-Check-in wird nur innerhalb von {radius} m vom Baustellenzentrum akzeptiert. Wenn GPS nicht verfügbar ist, bleibt die Demo klar als DEMO gekennzeichnet.", "Attendance history": "Anwesenheitsverlauf", records: "Einträge", "No records yet": "Noch keine Einträge", In: "Eingang", Out: "Ausgang", Complete: "Abgeschlossen", Duration: "Dauer", "Check-in blocked: you are {distance} m from the site. Move within {radius} m.": "Check-in blockiert: Du bist {distance} m von der Baustelle entfernt. Gehe auf höchstens {radius} m heran.",
    "Create teams, choose leaders and allocate workers.": "Teams erstellen, Leiter festlegen und Mitarbeiter zuweisen.", "New team": "Neues Team", "No teams yet": "Noch keine Teams", "Create the first team and add workers.": "Erstelle das erste Team und füge Mitarbeiter hinzu.", "Create team": "Team erstellen", "Edit team": "Team bearbeiten", "Team operational settings": "Betriebseinstellungen des Teams", "Delete team?": "Team löschen?", "The team will be removed from assigned projects. Worker profiles will not be deleted.": "Das Team wird von zugewiesenen Baustellen entfernt. Mitarbeiterprofile werden nicht gelöscht.", Assigned: "Zugewiesen", Available: "Verfügbar", "No project assigned": "Keine Baustelle zugewiesen", members: "Mitglieder", Trust: "Vertrauen", "Team name": "Teamname", "E.g. South Structure Team": "Z. B. Team Struktur Süd", Specialty: "Fachgebiet", Description: "Beschreibung", Inactive: "Inaktiv", "No project": "Keine Baustelle", "Assigned project": "Zugewiesene Baustelle", "Assign the leader or remove members.": "Leiter festlegen oder Mitglieder entfernen.", "Team has no members": "Team hat keine Mitglieder", "Add workers": "Mitarbeiter hinzufügen", "Profiles available in the WORKLY network.": "Im WORKLY-Netzwerk verfügbare Profile.",
    About: "Über", Phone: "Telefon", Country: "Land", Age: "Alter", "Professional indicators": "Berufliche Kennzahlen", "Overall rating": "Gesamtbewertung", Skills: "Kompetenzen", "Editable levels in your profile.": "Bearbeitbare Stufen in deinem Profil.", "Edit Worker profile": "Mitarbeiterprofil bearbeiten", "Changes are stored in this demo.": "Änderungen werden in dieser Demo gespeichert.", Name: "Name", Trade: "Beruf", "Professional bio": "Berufliche Biografie", "Skills — one per line: Name:Level": "Kompetenzen — eine pro Zeile: Name:Stufe", Company: "Unternehmen", "Tax ID": "Steuernummer", "Operational capacity": "Betriebskapazität", Projects: "Baustellen", Documents: "Dokumente", "Edit Company profile": "Unternehmensprofil bearbeiten", "Company name": "Unternehmensname", Industry: "Branche",
    "Profile updated.": "Profil aktualisiert.", "Company updated.": "Unternehmen aktualisiert.", "Team created.": "Team erstellt.", "Team updated.": "Team aktualisiert.", "Team deleted.": "Team gelöscht.", "Worker added.": "Mitarbeiter hinzugefügt.", "Worker removed.": "Mitarbeiter entfernt.", "Leader assigned.": "Leiter festgelegt.", "Project created.": "Baustelle erstellt.", "Project updated.": "Baustelle aktualisiert.", "Project deleted.": "Baustelle gelöscht.", "Assignment completed.": "Zuweisung abgeschlossen.", "Check-in saved in demo mode because the network is unavailable.": "Check-in im Demo-Modus gespeichert, da das Netzwerk nicht verfügbar ist.", "Check-in recorded.": "Check-in erfasst.", "Check-out recorded.": "Check-out erfasst.", "Demo data reset.": "Demo-Daten zurückgesetzt.", WORKER: "MITARBEITER", COMPANY: "UNTERNEHMEN"
  },
  nl: {
    "Operation under control": "Operatie onder controle", "workers on site": "medewerkers op bouwplaats", "Find talent": "Talent zoeken", "Manage teams": "Teams beheren", "Active projects": "Actieve bouwplaatsen", total: "in totaal", Teams: "Teams", professionals: "professionals", "On site now": "Nu op bouwplaats", "Active attendance": "Actieve aanwezigheid", Contracts: "Contracten", "Available to view": "In te zien", "Team monitoring": "Teammonitoring", "Active check-ins and operational status": "Actieve check-ins en operationele status", "View all attendance": "Alle aanwezigheid bekijken", "View all": "Alles bekijken", "No active attendance right now.": "Momenteel geen actieve aanwezigheid.", "Project pulse": "Bouwplaatsstatus", "Progress across key sites": "Voortgang van belangrijke bouwplaatsen", "Manage projects": "Bouwplaatsen beheren", Manage: "Beheren", "Recorded hours": "Geregistreerde uren", "Recent demo records": "Recente demo-registraties", "Valid and viewable": "Geldig en inzichtelijk", "Professional portfolio": "Professioneel portfolio", "Available in records": "Beschikbaar in archief", "Current project": "Huidige bouwplaats", "Work session active": "Actieve werksessie", "Ready to check in": "Klaar om in te checken", Schedule: "Werktijden", "Expected end": "Verwachte einddatum", Location: "Locatie", "No project has been assigned yet.": "Er is nog geen bouwplaats toegewezen.", "Next shift": "Volgende dienst", "Daily planning": "Dagplanning", "View schedule": "Werktijden bekijken", "No assigned project": "Geen bouwplaats toegewezen", "Check-in available near the site.": "Check-in beschikbaar in de buurt van de bouwplaats.", "View attendance": "Aanwezigheid bekijken", "Top skills": "Topvaardigheden", "Validated professional development": "Gevalideerde professionele ontwikkeling", "Edit skills": "Vaardigheden bewerken", "On site": "Op bouwplaats", "WORKER PULSE": "MEDEWERKERSTATUS",
    "Control centre for check-ins, check-outs and site GPS zones.": "Controlecentrum voor check-ins, check-outs en GPS-zones van bouwplaatsen.", "Show all": "Alles tonen", "Active only": "Alleen actief", "Active sessions": "Actieve sessies", "Inside geofence": "Binnen GPS-zone", "Radius set per site": "Straal per bouwplaats", "Completed records": "Afgeronde registraties", "Location source": "Locatiebron", "Configurable operational geofence per site.": "Configureerbare operationele GPS-zone per bouwplaats.", "No records for this filter": "Geen registraties voor dit filter", "Location-protected check-in, schedule and attendance history.": "Locatiebeveiligde check-in, werktijden en aanwezigheidsgeschiedenis.", "Active session": "Actieve sessie", "Ready to validate site zone": "Klaar om de bouwplaatszone te controleren", Since: "Sinds", "GPS obtained · distance unavailable": "GPS ontvangen · afstand niet beschikbaar", "GPS validated · {distance} m from site centre": "GPS gevalideerd · {distance} m van het bouwplaatscentrum", "Outside zone · {distance} m from site centre": "Buiten zone · {distance} m van het bouwplaatscentrum", "Demo mode · no real GPS validation": "Demomodus · geen echte GPS-validatie", "Authorised zone: {radius} m radius": "Toegestane zone: straal van {radius} m", "Validate GPS and check in": "GPS valideren en inchecken", "GPS check-in is accepted only within {radius} m of the site centre. If GPS is unavailable, the demo continues clearly marked as DEMO.": "GPS-check-in wordt alleen geaccepteerd binnen {radius} m van het bouwplaatscentrum. Als GPS niet beschikbaar is, blijft de demo duidelijk gemarkeerd als DEMO.", "Attendance history": "Aanwezigheidsgeschiedenis", records: "registraties", "No records yet": "Nog geen registraties", In: "In", Out: "Uit", Complete: "Voltooid", Duration: "Duur", "Check-in blocked: you are {distance} m from the site. Move within {radius} m.": "Check-in geblokkeerd: je bent {distance} m van de bouwplaats. Ga tot binnen {radius} m.",
    "Create teams, choose leaders and allocate workers.": "Maak teams, kies leiders en wijs medewerkers toe.", "New team": "Nieuw team", "No teams yet": "Nog geen teams", "Create the first team and add workers.": "Maak het eerste team en voeg medewerkers toe.", "Create team": "Team maken", "Edit team": "Team bewerken", "Team operational settings": "Operationele teaminstellingen", "Delete team?": "Team verwijderen?", "The team will be removed from assigned projects. Worker profiles will not be deleted.": "Het team wordt van toegewezen bouwplaatsen verwijderd. Medewerkerprofielen worden niet verwijderd.", Assigned: "Toegewezen", Available: "Beschikbaar", "No project assigned": "Geen bouwplaats toegewezen", members: "leden", Trust: "Vertrouwen", "Team name": "Teamnaam", "E.g. South Structure Team": "Bijv. Team Structuur Zuid", Specialty: "Specialisme", Description: "Beschrijving", Inactive: "Inactief", "No project": "Geen bouwplaats", "Assigned project": "Toegewezen bouwplaats", "Assign the leader or remove members.": "Wijs de leider aan of verwijder leden.", "Team has no members": "Team heeft geen leden", "Add workers": "Medewerkers toevoegen", "Profiles available in the WORKLY network.": "Profielen beschikbaar in het WORKLY-netwerk.",
    About: "Over", Phone: "Telefoon", Country: "Land", Age: "Leeftijd", "Professional indicators": "Professionele indicatoren", "Overall rating": "Algemene beoordeling", Skills: "Vaardigheden", "Editable levels in your profile.": "Bewerkbare niveaus in je profiel.", "Edit Worker profile": "Medewerkerprofiel bewerken", "Changes are stored in this demo.": "Wijzigingen worden in deze demo opgeslagen.", Name: "Naam", Trade: "Beroep", "Professional bio": "Professionele biografie", "Skills — one per line: Name:Level": "Vaardigheden — één per regel: Naam:Niveau", Company: "Bedrijf", "Tax ID": "Fiscaal nummer", "Operational capacity": "Operationele capaciteit", Projects: "Bouwplaatsen", Documents: "Documenten", "Edit Company profile": "Bedrijfsprofiel bewerken", "Company name": "Bedrijfsnaam", Industry: "Sector",
    "Profile updated.": "Profiel bijgewerkt.", "Company updated.": "Bedrijf bijgewerkt.", "Team created.": "Team aangemaakt.", "Team updated.": "Team bijgewerkt.", "Team deleted.": "Team verwijderd.", "Worker added.": "Medewerker toegevoegd.", "Worker removed.": "Medewerker verwijderd.", "Leader assigned.": "Leider toegewezen.", "Project created.": "Bouwplaats aangemaakt.", "Project updated.": "Bouwplaats bijgewerkt.", "Project deleted.": "Bouwplaats verwijderd.", "Assignment completed.": "Toewijzing voltooid.", "Check-in saved in demo mode because the network is unavailable.": "Check-in opgeslagen in demomodus omdat het netwerk niet beschikbaar is.", "Check-in recorded.": "Check-in geregistreerd.", "Check-out recorded.": "Check-out geregistreerd.", "Demo data reset.": "Demogegevens gereset.", WORKER: "MEDEWERKER", COMPANY: "BEDRIJF"
  }
};

export function uiText(language: LanguageCode, portuguese: string, english: string) {
  if (language === "pt" || language === "en") return baseUiText(language, portuguese, english);
  return extra[language][english] ?? baseUiText(language, portuguese, english);
}

export function uiFormat(language: LanguageCode, portuguese: string, english: string, variables: Variables) {
  if (language === "pt" || language === "en") return baseUiFormat(language, portuguese, english, variables);
  const template = extra[language][english] ?? baseUiText(language, portuguese, english);
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match,
  );
}

export function localeForLanguage(language: LanguageCode) {
  const locales: Record<LanguageCode, string> = {
    pt: "pt-PT",
    en: "en-GB",
    fr: "fr-FR",
    es: "es-ES",
    ro: "ro-RO",
    de: "de-DE",
    nl: "nl-NL",
  };
  return locales[language];
}
