import type { LanguageCode } from "./types";

type SecondaryLanguage = Exclude<LanguageCode, "pt" | "en">;

type Variables = Record<string, string | number>;

const catalog: Record<SecondaryLanguage, Record<string, string>> = {
  fr: {
    Identity: "Identification",
    Insurance: "Assurance",
    Medical: "Santé",
    Safety: "Sécurité",
    Technical: "Technique",
    Planning: "Planification",
    Legal: "Juridique",
    License: "Licence",
    "Archive organised by worker and project, with immediate access to every document.": "Archive organisée par travailleur et par chantier, avec accès immédiat à chaque document.",
    "Valid professional certifications ready to view.": "Certifications professionnelles valides, prêtes à être consultées.",
    "A portfolio of verified work and on-site results.": "Un portefeuille de travaux vérifiés et de résultats sur chantier.",
    "Contracts linked to workers, companies and projects.": "Contrats liés aux travailleurs, aux entreprises et aux chantiers.",
    Personal: "Personnel",
    Workers: "Travailleurs",
    "Your documents": "Vos documents",
    workers: "travailleurs",
    Projects: "Chantiers",
    projects: "chantiers",
    Company: "Entreprise",
    "Legal archive": "Archive juridique",
    Updated: "Mis à jour",
    "Protected archive": "Archive protégée",
    "Search worker...": "Rechercher un travailleur...",
    "Search project...": "Rechercher un chantier...",
    "Personal folder": "Dossier personnel",
    "Select a folder to see only that worker's documents.": "Sélectionnez un dossier pour afficher uniquement les documents de ce travailleur.",
    "No results": "Aucun résultat",
    Documents: "Documents",
    Certificates: "Certificats",
    Contracts: "Contrats",
    "Empty folder": "Dossier vide",
    "No workers": "Aucun travailleur",
    "Each project has its own technical archive.": "Chaque chantier possède sa propre archive technique.",
    Progress: "Progression",
    "Contracts linked to project": "Contrats liés au chantier",
    Worker: "Travailleur",
    "No contracts are linked to this project yet.": "Aucun contrat n’est encore lié à ce chantier.",
    "No projects": "Aucun chantier",
    "Institutional and legal company documents": "Documents institutionnels et juridiques de l’entreprise",
    "Empty archive": "Archive vide",
    "Signed by both parties": "Signé par les deux parties",
    "Signature pending": "Signature en attente",
    "Fictitious certificate issued by {issuer}, viewable to demonstrate WORKLY document validation.": "Certificat fictif émis par {issuer}, consultable pour démontrer la validation documentaire WORKLY.",
    "Valid until": "Valide jusqu’au",
    "View project": "Voir le projet",
    "No featured projects": "Aucun projet mis en avant",
    "Fictitious content created exclusively for the WORKLY demo. No legal validity.": "Contenu fictif créé exclusivement pour la démonstration WORKLY. Sans valeur juridique.",
    "Select an item to view it.": "Sélectionnez un élément pour le consulter.",
    Valid: "Valide",
    Active: "Actif",
    Expired: "Expiré",
    Pending: "En attente",
    Open: "Consulter",
    "Safety and Health Plan": "Plan de sécurité et de santé",
    "Assembly drawings and parts": "Plans et pièces de montage",
    "Planning and schedule": "Planification et calendrier",
    "Demonstration Safety and Health Plan for {project}. Includes preventive organisation, access rules, main risks and site control measures.": "Plan de sécurité et de santé de démonstration pour {project}. Il comprend l’organisation préventive, les règles d’accès, les principaux risques et les mesures de contrôle du chantier.",
    "Demonstration technical package associated with {project}: layout, assembly references, intervention zones and execution notes.": "Dossier technique de démonstration associé à {project} : implantation, références de montage, zones d’intervention et notes d’exécution.",
    "Demonstration schedule for {project}, covering {start} to {end}, working hours {schedule} and current progress of {progress}%.": "Planning de démonstration du chantier {project}, couvrant la période du {start} au {end}, avec les horaires {schedule} et une progression actuelle de {progress} %.",
    "Planning, progress and resources by project.": "Planification, progression et ressources par chantier.",
    "Assigned projects, locations and schedules.": "Chantiers attribués, lieux et horaires.",
    "New project": "Nouveau chantier",
    "No projects yet": "Aucun chantier pour le moment",
    "Create the first project and assign a team.": "Créez le premier chantier et attribuez-lui une équipe.",
    "The company has not assigned a project to your profile yet.": "L’entreprise n’a pas encore attribué de chantier à votre profil.",
    "Create project": "Créer un chantier",
    "Edit project": "Modifier le chantier",
    "Operational details and schedule": "Informations opérationnelles et calendrier",
    "Delete project?": "Supprimer le chantier ?",
    "The project will be removed and assigned teams will become available. Historical attendance remains in the demo.": "Le chantier sera supprimé et les équipes affectées redeviendront disponibles. L’historique des présences reste conservé dans la démonstration.",
    teams: "équipes",
    people: "personnes",
    "Project name": "Nom du chantier",
    Client: "Client",
    Location: "Localisation",
    Description: "Description",
    "Start date": "Date de début",
    "End date": "Date de fin",
    Schedule: "Horaires",
    Latitude: "Latitude",
    Longitude: "Longitude",
    "GPS radius (50–2000 m)": "Rayon GPS (50–2000 m)",
    complete: "terminé",
    "GPS zone": "Zone GPS",
    "Coordinates not configured": "Coordonnées non configurées",
    Period: "Période",
    "Select to assign or remove.": "Sélectionnez pour attribuer ou retirer.",
    "Search, profiles, certificates and assignments.": "Recherche, profils, certificats et affectations.",
    "Name, trade, skill…": "Nom, métier, compétence…",
    "Clear search": "Effacer la recherche",
    All: "Tous",
    results: "résultats",
    "Change filters or search for another skill.": "Modifiez les filtres ou recherchez une autre compétence.",
    "Fictitious file available only to demonstrate the workflow.": "Fichier fictif disponible uniquement pour démontrer le flux de travail.",
    Skills: "Compétences",
    Assignments: "Affectations",
    "Add to a team or project.": "Ajouter à une équipe ou à un chantier.",
    Trade: "Métier",
    Phone: "Téléphone",
    Bio: "Biographie",
    "Operations Map": "Carte des opérations",
    "Real-time view of company sites, attendance and GPS zones.": "Vue en temps réel des chantiers, des présences et des zones GPS de l’entreprise.",
    "LIVE OPS": "OPÉRATIONS LIVE",
    "Active sites": "Chantiers actifs",
    "sites monitored": "chantiers surveillés",
    "Workers on site": "Travailleurs sur chantier",
    "Open sessions": "Sessions ouvertes",
    "GPS validated": "GPS validé",
    "Inside geofence": "Dans la zone GPS",
    Alerts: "Alertes",
    "Outside or unverified GPS": "GPS hors zone ou non vérifié",
    "Site network": "Réseau de chantiers",
    "Relative position based on configured GPS coordinates.": "Position relative basée sur les coordonnées GPS configurées.",
    "on site": "sur chantier",
    Live: "En direct",
    Alert: "Alerte",
    Idle: "Sans session",
    "No geocoded sites": "Aucun chantier géolocalisé",
    "Set latitude and longitude on the project to include it in the operations map.": "Définissez la latitude et la longitude du chantier pour l’inclure dans la carte des opérations.",
    Operating: "En opération",
    "GPS centre": "Centre GPS",
    Radius: "Rayon",
    "On site": "Sur chantier",
    "{count} session(s) require GPS attention.": "{count} session(s) nécessitent une vérification GPS.",
    "No active GPS violations on this site.": "Aucune violation GPS active sur ce chantier.",
    OUT: "HORS ZONE",
    CHECK: "VÉRIFIER",
    "No worker has an active session on this site.": "Aucun travailleur n’a de session active sur ce chantier.",
    "No sites": "Aucun chantier",
    "All site status": "État de tous les chantiers",
    "Select a site to highlight it on the map.": "Sélectionnez un chantier pour le mettre en évidence sur la carte.",
    Attention: "Attention",
  },
  es: {
    Identity: "Identificación", Insurance: "Seguro", Medical: "Salud", Safety: "Seguridad", Technical: "Técnico", Planning: "Planificación", Legal: "Legal", License: "Licencia",
    "Archive organised by worker and project, with immediate access to every document.": "Archivo organizado por trabajador y obra, con acceso inmediato a cada documento.",
    "Valid professional certifications ready to view.": "Certificaciones profesionales válidas y listas para consultar.",
    "A portfolio of verified work and on-site results.": "Portafolio de trabajos verificados y resultados en obra.",
    "Contracts linked to workers, companies and projects.": "Contratos vinculados a trabajadores, empresas y obras.",
    Personal: "Personales", Workers: "Trabajadores", "Your documents": "Tus documentos", workers: "trabajadores", Projects: "Obras", projects: "obras", Company: "Empresa", "Legal archive": "Archivo legal", Updated: "Actualizado", "Protected archive": "Archivo protegido",
    "Search worker...": "Buscar trabajador...", "Search project...": "Buscar obra...", "Personal folder": "Carpeta personal", "Select a folder to see only that worker's documents.": "Selecciona una carpeta para ver solo los documentos de ese trabajador.", "No results": "Sin resultados", Documents: "Documentos", Certificates: "Certificados", Contracts: "Contratos", "Empty folder": "Carpeta vacía", "No workers": "Sin trabajadores", "Each project has its own technical archive.": "Cada obra tiene su propio archivo técnico.", Progress: "Progreso", "Contracts linked to project": "Contratos vinculados a la obra", Worker: "Trabajador", "No contracts are linked to this project yet.": "Todavía no hay contratos vinculados a esta obra.", "No projects": "Sin obras", "Institutional and legal company documents": "Documentos institucionales y legales de la empresa", "Empty archive": "Archivo vacío", "Signed by both parties": "Firmado por ambas partes", "Signature pending": "Firma pendiente", "Fictitious certificate issued by {issuer}, viewable to demonstrate WORKLY document validation.": "Certificado ficticio emitido por {issuer}, consultable para demostrar la validación documental de WORKLY.", "Valid until": "Válido hasta", "View project": "Ver proyecto", "No featured projects": "Sin proyectos destacados", "Fictitious content created exclusively for the WORKLY demo. No legal validity.": "Contenido ficticio creado exclusivamente para la demostración de WORKLY. Sin validez legal.", "Select an item to view it.": "Selecciona un elemento para consultarlo.", Valid: "Válido", Active: "Activo", Expired: "Caducado", Pending: "Pendiente", Open: "Consultar",
    "Safety and Health Plan": "Plan de Seguridad y Salud", "Assembly drawings and parts": "Planos y piezas de montaje", "Planning and schedule": "Planificación y cronograma", "Demonstration Safety and Health Plan for {project}. Includes preventive organisation, access rules, main risks and site control measures.": "Plan de Seguridad y Salud de demostración para {project}. Incluye organización preventiva, normas de acceso, riesgos principales y medidas de control de la obra.", "Demonstration technical package associated with {project}: layout, assembly references, intervention zones and execution notes.": "Paquete técnico de demostración asociado a {project}: implantación, referencias de montaje, zonas de intervención y notas de ejecución.", "Demonstration schedule for {project}, covering {start} to {end}, working hours {schedule} and current progress of {progress}%.": "Cronograma de demostración de {project}, desde {start} hasta {end}, con horario {schedule} y progreso actual del {progress}%.",
    "Planning, progress and resources by project.": "Planificación, progreso y recursos por obra.", "Assigned projects, locations and schedules.": "Obras asignadas, ubicaciones y horarios.", "New project": "Nueva obra", "No projects yet": "Aún no hay obras", "Create the first project and assign a team.": "Crea la primera obra y asigna un equipo.", "The company has not assigned a project to your profile yet.": "La empresa todavía no ha asignado una obra a tu perfil.", "Create project": "Crear obra", "Edit project": "Editar obra", "Operational details and schedule": "Información operativa y calendario", "Delete project?": "¿Eliminar obra?", "The project will be removed and assigned teams will become available. Historical attendance remains in the demo.": "La obra se eliminará y los equipos asignados volverán a estar disponibles. El historial de asistencia se mantiene en la demostración.", teams: "equipos", people: "personas", "Project name": "Nombre de la obra", Client: "Cliente", Location: "Ubicación", Description: "Descripción", "Start date": "Fecha de inicio", "End date": "Fecha de fin", Schedule: "Horario", Latitude: "Latitud", Longitude: "Longitud", "GPS radius (50–2000 m)": "Radio GPS (50–2000 m)", complete: "completado", "GPS zone": "Zona GPS", "Coordinates not configured": "Coordenadas sin configurar", Period: "Periodo", "Select to assign or remove.": "Selecciona para asignar o quitar.",
    "Search, profiles, certificates and assignments.": "Búsqueda, perfiles, certificados y asignaciones.", "Name, trade, skill…": "Nombre, profesión, competencia…", "Clear search": "Limpiar búsqueda", All: "Todos", results: "resultados", "Change filters or search for another skill.": "Cambia los filtros o busca otra competencia.", "Fictitious file available only to demonstrate the workflow.": "Archivo ficticio disponible solo para demostrar el flujo de trabajo.", Skills: "Competencias", Assignments: "Asignaciones", "Add to a team or project.": "Añadir a un equipo o una obra.", Trade: "Profesión", Phone: "Teléfono", Bio: "Biografía",
    "Operations Map": "Mapa operativo", "Real-time view of company sites, attendance and GPS zones.": "Vista en tiempo real de las obras, la asistencia y las zonas GPS de la empresa.", "LIVE OPS": "OPERACIONES EN VIVO", "Active sites": "Obras activas", "sites monitored": "obras monitorizadas", "Workers on site": "Trabajadores en obra", "Open sessions": "Sesiones abiertas", "GPS validated": "GPS validado", "Inside geofence": "Dentro de la geocerca", Alerts: "Alertas", "Outside or unverified GPS": "GPS fuera o sin verificar", "Site network": "Red de obras", "Relative position based on configured GPS coordinates.": "Posición relativa basada en las coordenadas GPS configuradas.", "on site": "en obra", Live: "En vivo", Alert: "Alerta", Idle: "Sin sesión", "No geocoded sites": "Sin obras geolocalizadas", "Set latitude and longitude on the project to include it in the operations map.": "Define la latitud y la longitud de la obra para incluirla en el mapa operativo.", Operating: "En operación", "GPS centre": "Centro GPS", Radius: "Radio", "On site": "En obra", "{count} session(s) require GPS attention.": "{count} sesión(es) requieren atención GPS.", "No active GPS violations on this site.": "No hay infracciones GPS activas en esta obra.", OUT: "FUERA", CHECK: "VERIFICAR", "No worker has an active session on this site.": "Ningún trabajador tiene una sesión activa en esta obra.", "No sites": "Sin obras", "All site status": "Estado de todas las obras", "Select a site to highlight it on the map.": "Selecciona una obra para destacarla en el mapa.", Attention: "Atención",
  },
  ro: {
    Identity: "Identificare", Insurance: "Asigurare", Medical: "Medical", Safety: "Siguranță", Technical: "Tehnic", Planning: "Planificare", Legal: "Juridic", License: "Licență",
    "Archive organised by worker and project, with immediate access to every document.": "Arhivă organizată pe lucrător și șantier, cu acces imediat la fiecare document.", "Valid professional certifications ready to view.": "Certificări profesionale valabile, gata de consultat.", "A portfolio of verified work and on-site results.": "Portofoliu de lucrări verificate și rezultate din șantier.", "Contracts linked to workers, companies and projects.": "Contracte asociate lucrătorilor, companiilor și șantierelor.", Personal: "Personale", Workers: "Lucrători", "Your documents": "Documentele tale", workers: "lucrători", Projects: "Șantiere", projects: "șantiere", Company: "Companie", "Legal archive": "Arhivă juridică", Updated: "Actualizat", "Protected archive": "Arhivă protejată", "Search worker...": "Caută lucrător...", "Search project...": "Caută șantier...", "Personal folder": "Dosar personal", "Select a folder to see only that worker's documents.": "Selectează un dosar pentru a vedea doar documentele acelui lucrător.", "No results": "Niciun rezultat", Documents: "Documente", Certificates: "Certificate", Contracts: "Contracte", "Empty folder": "Dosar gol", "No workers": "Niciun lucrător", "Each project has its own technical archive.": "Fiecare șantier are propria arhivă tehnică.", Progress: "Progres", "Contracts linked to project": "Contracte asociate șantierului", Worker: "Lucrător", "No contracts are linked to this project yet.": "Nu există încă contracte asociate acestui șantier.", "No projects": "Niciun șantier", "Institutional and legal company documents": "Documente instituționale și juridice ale companiei", "Empty archive": "Arhivă goală", "Signed by both parties": "Semnat de ambele părți", "Signature pending": "Semnătură în așteptare", "Fictitious certificate issued by {issuer}, viewable to demonstrate WORKLY document validation.": "Certificat fictiv emis de {issuer}, disponibil pentru demonstrarea validării documentelor WORKLY.", "Valid until": "Valabil până la", "View project": "Vezi proiectul", "No featured projects": "Niciun proiect evidențiat", "Fictitious content created exclusively for the WORKLY demo. No legal validity.": "Conținut fictiv creat exclusiv pentru demonstrația WORKLY. Fără valabilitate juridică.", "Select an item to view it.": "Selectează un element pentru a-l consulta.", Valid: "Valabil", Active: "Activ", Expired: "Expirat", Pending: "În așteptare", Open: "Deschide",
    "Safety and Health Plan": "Plan de securitate și sănătate", "Assembly drawings and parts": "Desene și piese de montaj", "Planning and schedule": "Planificare și grafic", "Demonstration Safety and Health Plan for {project}. Includes preventive organisation, access rules, main risks and site control measures.": "Plan demonstrativ de securitate și sănătate pentru {project}. Include organizarea prevenirii, regulile de acces, riscurile principale și măsurile de control ale șantierului.", "Demonstration technical package associated with {project}: layout, assembly references, intervention zones and execution notes.": "Pachet tehnic demonstrativ asociat cu {project}: amplasare, referințe de montaj, zone de intervenție și note de execuție.", "Demonstration schedule for {project}, covering {start} to {end}, working hours {schedule} and current progress of {progress}%.": "Program demonstrativ pentru {project}, din {start} până în {end}, cu orarul {schedule} și progresul actual de {progress}%.",
    "Planning, progress and resources by project.": "Planificare, progres și resurse pe șantier.", "Assigned projects, locations and schedules.": "Șantiere atribuite, locații și programe.", "New project": "Șantier nou", "No projects yet": "Nu există încă șantiere", "Create the first project and assign a team.": "Creează primul șantier și atribuie o echipă.", "The company has not assigned a project to your profile yet.": "Compania nu a atribuit încă un șantier profilului tău.", "Create project": "Creează șantier", "Edit project": "Editează șantier", "Operational details and schedule": "Detalii operaționale și program", "Delete project?": "Ștergi șantierul?", "The project will be removed and assigned teams will become available. Historical attendance remains in the demo.": "Șantierul va fi șters, iar echipele alocate vor redeveni disponibile. Istoricul prezenței rămâne în demonstrație.", teams: "echipe", people: "persoane", "Project name": "Numele șantierului", Client: "Client", Location: "Locație", Description: "Descriere", "Start date": "Data începerii", "End date": "Data finalizării", Schedule: "Program", Latitude: "Latitudine", Longitude: "Longitudine", "GPS radius (50–2000 m)": "Rază GPS (50–2000 m)", complete: "finalizat", "GPS zone": "Zonă GPS", "Coordinates not configured": "Coordonate neconfigurate", Period: "Perioadă", "Select to assign or remove.": "Selectează pentru atribuire sau eliminare.",
    "Search, profiles, certificates and assignments.": "Căutare, profiluri, certificate și alocări.", "Name, trade, skill…": "Nume, meserie, competență…", "Clear search": "Șterge căutarea", All: "Toți", results: "rezultate", "Change filters or search for another skill.": "Schimbă filtrele sau caută o altă competență.", "Fictitious file available only to demonstrate the workflow.": "Fișier fictiv disponibil doar pentru demonstrarea fluxului.", Skills: "Competențe", Assignments: "Alocări", "Add to a team or project.": "Adaugă într-o echipă sau pe un șantier.", Trade: "Meserie", Phone: "Telefon", Bio: "Biografie",
    "Operations Map": "Hartă operațională", "Real-time view of company sites, attendance and GPS zones.": "Vizualizare în timp real a șantierelor, prezenței și zonelor GPS ale companiei.", "LIVE OPS": "OPERAȚIUNI LIVE", "Active sites": "Șantiere active", "sites monitored": "șantiere monitorizate", "Workers on site": "Lucrători pe șantier", "Open sessions": "Sesiuni deschise", "GPS validated": "GPS validat", "Inside geofence": "În zona GPS", Alerts: "Alerte", "Outside or unverified GPS": "GPS în afara zonei sau neverificat", "Site network": "Rețeaua șantierelor", "Relative position based on configured GPS coordinates.": "Poziție relativă bazată pe coordonatele GPS configurate.", "on site": "pe șantier", Live: "Live", Alert: "Alertă", Idle: "Fără sesiune", "No geocoded sites": "Niciun șantier geolocalizat", "Set latitude and longitude on the project to include it in the operations map.": "Configurează latitudinea și longitudinea șantierului pentru a-l include pe harta operațională.", Operating: "În operare", "GPS centre": "Centru GPS", Radius: "Rază", "On site": "Pe șantier", "{count} session(s) require GPS attention.": "{count} sesiune/sesiuni necesită atenție GPS.", "No active GPS violations on this site.": "Nu există încălcări GPS active pe acest șantier.", OUT: "AFARĂ", CHECK: "VERIFICĂ", "No worker has an active session on this site.": "Niciun lucrător nu are o sesiune activă pe acest șantier.", "No sites": "Niciun șantier", "All site status": "Starea tuturor șantierelor", "Select a site to highlight it on the map.": "Selectează un șantier pentru a-l evidenția pe hartă.", Attention: "Atenție",
  },
  de: {
    Identity: "Identifikation", Insurance: "Versicherung", Medical: "Gesundheit", Safety: "Sicherheit", Technical: "Technisch", Planning: "Planung", Legal: "Rechtlich", License: "Lizenz",
    "Archive organised by worker and project, with immediate access to every document.": "Archiv nach Mitarbeiter und Baustelle organisiert, mit direktem Zugriff auf jedes Dokument.", "Valid professional certifications ready to view.": "Gültige berufliche Zertifizierungen zur direkten Einsicht.", "A portfolio of verified work and on-site results.": "Portfolio verifizierter Arbeiten und Baustellenergebnisse.", "Contracts linked to workers, companies and projects.": "Verträge, die Mitarbeitern, Unternehmen und Baustellen zugeordnet sind.", Personal: "Persönlich", Workers: "Mitarbeiter", "Your documents": "Deine Dokumente", workers: "Mitarbeiter", Projects: "Baustellen", projects: "Baustellen", Company: "Unternehmen", "Legal archive": "Rechtsarchiv", Updated: "Aktualisiert", "Protected archive": "Geschütztes Archiv", "Search worker...": "Mitarbeiter suchen...", "Search project...": "Baustelle suchen...", "Personal folder": "Persönlicher Ordner", "Select a folder to see only that worker's documents.": "Wähle einen Ordner, um nur die Dokumente dieses Mitarbeiters zu sehen.", "No results": "Keine Ergebnisse", Documents: "Dokumente", Certificates: "Zertifikate", Contracts: "Verträge", "Empty folder": "Leerer Ordner", "No workers": "Keine Mitarbeiter", "Each project has its own technical archive.": "Jede Baustelle besitzt ein eigenes technisches Archiv.", Progress: "Fortschritt", "Contracts linked to project": "Der Baustelle zugeordnete Verträge", Worker: "Mitarbeiter", "No contracts are linked to this project yet.": "Dieser Baustelle sind noch keine Verträge zugeordnet.", "No projects": "Keine Baustellen", "Institutional and legal company documents": "Institutionelle und rechtliche Unternehmensdokumente", "Empty archive": "Leeres Archiv", "Signed by both parties": "Von beiden Parteien unterzeichnet", "Signature pending": "Unterschrift ausstehend", "Fictitious certificate issued by {issuer}, viewable to demonstrate WORKLY document validation.": "Fiktives Zertifikat von {issuer}, einsehbar zur Demonstration der WORKLY-Dokumentenprüfung.", "Valid until": "Gültig bis", "View project": "Projekt ansehen", "No featured projects": "Keine hervorgehobenen Projekte", "Fictitious content created exclusively for the WORKLY demo. No legal validity.": "Fiktiver Inhalt ausschließlich für die WORKLY-Demo. Keine rechtliche Gültigkeit.", "Select an item to view it.": "Wähle einen Eintrag zur Ansicht aus.", Valid: "Gültig", Active: "Aktiv", Expired: "Abgelaufen", Pending: "Ausstehend", Open: "Öffnen",
    "Safety and Health Plan": "Sicherheits- und Gesundheitsschutzplan", "Assembly drawings and parts": "Montagezeichnungen und Bauteile", "Planning and schedule": "Planung und Terminplan", "Demonstration Safety and Health Plan for {project}. Includes preventive organisation, access rules, main risks and site control measures.": "Demonstrations-Sicherheits- und Gesundheitsschutzplan für {project}. Enthält Präventionsorganisation, Zugangsregeln, Hauptrisiken und Kontrollmaßnahmen der Baustelle.", "Demonstration technical package associated with {project}: layout, assembly references, intervention zones and execution notes.": "Technisches Demopaket für {project}: Lageplan, Montagereferenzen, Arbeitsbereiche und Ausführungshinweise.", "Demonstration schedule for {project}, covering {start} to {end}, working hours {schedule} and current progress of {progress}%.": "Demo-Terminplan für {project} vom {start} bis {end}, Arbeitszeit {schedule} und aktueller Fortschritt {progress}%.",
    "Planning, progress and resources by project.": "Planung, Fortschritt und Ressourcen je Baustelle.", "Assigned projects, locations and schedules.": "Zugewiesene Baustellen, Standorte und Arbeitszeiten.", "New project": "Neue Baustelle", "No projects yet": "Noch keine Baustellen", "Create the first project and assign a team.": "Erstelle die erste Baustelle und weise ein Team zu.", "The company has not assigned a project to your profile yet.": "Das Unternehmen hat deinem Profil noch keine Baustelle zugewiesen.", "Create project": "Baustelle erstellen", "Edit project": "Baustelle bearbeiten", "Operational details and schedule": "Betriebsdaten und Zeitplan", "Delete project?": "Baustelle löschen?", "The project will be removed and assigned teams will become available. Historical attendance remains in the demo.": "Die Baustelle wird entfernt und zugewiesene Teams werden wieder verfügbar. Historische Anwesenheitsdaten bleiben in der Demo erhalten.", teams: "Teams", people: "Personen", "Project name": "Baustellenname", Client: "Kunde", Location: "Standort", Description: "Beschreibung", "Start date": "Startdatum", "End date": "Enddatum", Schedule: "Arbeitszeit", Latitude: "Breitengrad", Longitude: "Längengrad", "GPS radius (50–2000 m)": "GPS-Radius (50–2000 m)", complete: "abgeschlossen", "GPS zone": "GPS-Zone", "Coordinates not configured": "Koordinaten nicht konfiguriert", Period: "Zeitraum", "Select to assign or remove.": "Auswählen, um zuzuweisen oder zu entfernen.",
    "Search, profiles, certificates and assignments.": "Suche, Profile, Zertifikate und Zuweisungen.", "Name, trade, skill…": "Name, Beruf, Kompetenz…", "Clear search": "Suche löschen", All: "Alle", results: "Ergebnisse", "Change filters or search for another skill.": "Filter ändern oder nach einer anderen Kompetenz suchen.", "Fictitious file available only to demonstrate the workflow.": "Fiktive Datei, die nur zur Demonstration des Ablaufs verfügbar ist.", Skills: "Kompetenzen", Assignments: "Zuweisungen", "Add to a team or project.": "Zu einem Team oder einer Baustelle hinzufügen.", Trade: "Beruf", Phone: "Telefon", Bio: "Biografie",
    "Operations Map": "Betriebskarte", "Real-time view of company sites, attendance and GPS zones.": "Echtzeitansicht der Baustellen, Anwesenheiten und GPS-Zonen des Unternehmens.", "LIVE OPS": "LIVE-BETRIEB", "Active sites": "Aktive Baustellen", "sites monitored": "überwachte Baustellen", "Workers on site": "Mitarbeiter auf Baustelle", "Open sessions": "Offene Sitzungen", "GPS validated": "GPS validiert", "Inside geofence": "Innerhalb der GPS-Zone", Alerts: "Warnungen", "Outside or unverified GPS": "GPS außerhalb oder nicht verifiziert", "Site network": "Baustellennetz", "Relative position based on configured GPS coordinates.": "Relative Position basierend auf den konfigurierten GPS-Koordinaten.", "on site": "auf Baustelle", Live: "Live", Alert: "Warnung", Idle: "Ohne Sitzung", "No geocoded sites": "Keine geolokalisierten Baustellen", "Set latitude and longitude on the project to include it in the operations map.": "Breiten- und Längengrad der Baustelle festlegen, um sie in die Betriebskarte aufzunehmen.", Operating: "In Betrieb", "GPS centre": "GPS-Zentrum", Radius: "Radius", "On site": "Auf Baustelle", "{count} session(s) require GPS attention.": "{count} Sitzung(en) erfordern eine GPS-Prüfung.", "No active GPS violations on this site.": "Keine aktiven GPS-Verstöße auf dieser Baustelle.", OUT: "AUSSERHALB", CHECK: "PRÜFEN", "No worker has an active session on this site.": "Kein Mitarbeiter hat eine aktive Sitzung auf dieser Baustelle.", "No sites": "Keine Baustellen", "All site status": "Status aller Baustellen", "Select a site to highlight it on the map.": "Wähle eine Baustelle aus, um sie auf der Karte hervorzuheben.", Attention: "Achtung",
  },
  nl: {
    Identity: "Identificatie", Insurance: "Verzekering", Medical: "Gezondheid", Safety: "Veiligheid", Technical: "Technisch", Planning: "Planning", Legal: "Juridisch", License: "Vergunning",
    "Archive organised by worker and project, with immediate access to every document.": "Archief georganiseerd per medewerker en bouwplaats, met directe toegang tot elk document.", "Valid professional certifications ready to view.": "Geldige beroepscertificaten direct beschikbaar voor inzage.", "A portfolio of verified work and on-site results.": "Portfolio van geverifieerd werk en resultaten op de bouwplaats.", "Contracts linked to workers, companies and projects.": "Contracten gekoppeld aan medewerkers, bedrijven en bouwplaatsen.", Personal: "Persoonlijk", Workers: "Medewerkers", "Your documents": "Jouw documenten", workers: "medewerkers", Projects: "Bouwplaatsen", projects: "bouwplaatsen", Company: "Bedrijf", "Legal archive": "Juridisch archief", Updated: "Bijgewerkt", "Protected archive": "Beveiligd archief", "Search worker...": "Medewerker zoeken...", "Search project...": "Bouwplaats zoeken...", "Personal folder": "Persoonlijke map", "Select a folder to see only that worker's documents.": "Selecteer een map om alleen de documenten van die medewerker te zien.", "No results": "Geen resultaten", Documents: "Documenten", Certificates: "Certificaten", Contracts: "Contracten", "Empty folder": "Lege map", "No workers": "Geen medewerkers", "Each project has its own technical archive.": "Elke bouwplaats heeft een eigen technisch archief.", Progress: "Voortgang", "Contracts linked to project": "Contracten gekoppeld aan bouwplaats", Worker: "Medewerker", "No contracts are linked to this project yet.": "Er zijn nog geen contracten aan deze bouwplaats gekoppeld.", "No projects": "Geen bouwplaatsen", "Institutional and legal company documents": "Institutionele en juridische bedrijfsdocumenten", "Empty archive": "Leeg archief", "Signed by both parties": "Door beide partijen ondertekend", "Signature pending": "Handtekening in afwachting", "Fictitious certificate issued by {issuer}, viewable to demonstrate WORKLY document validation.": "Fictief certificaat uitgegeven door {issuer}, beschikbaar om WORKLY-documentvalidatie te demonstreren.", "Valid until": "Geldig tot", "View project": "Project bekijken", "No featured projects": "Geen uitgelichte projecten", "Fictitious content created exclusively for the WORKLY demo. No legal validity.": "Fictieve inhoud uitsluitend gemaakt voor de WORKLY-demo. Niet rechtsgeldig.", "Select an item to view it.": "Selecteer een item om het te bekijken.", Valid: "Geldig", Active: "Actief", Expired: "Verlopen", Pending: "In afwachting", Open: "Openen",
    "Safety and Health Plan": "Veiligheids- en gezondheidsplan", "Assembly drawings and parts": "Montagetekeningen en onderdelen", "Planning and schedule": "Planning en tijdschema", "Demonstration Safety and Health Plan for {project}. Includes preventive organisation, access rules, main risks and site control measures.": "Demonstratieplan voor veiligheid en gezondheid voor {project}. Bevat preventieorganisatie, toegangsregels, belangrijkste risico’s en beheersmaatregelen op de bouwplaats.", "Demonstration technical package associated with {project}: layout, assembly references, intervention zones and execution notes.": "Technisch demonstratiepakket voor {project}: indeling, montagereferenties, werkzones en uitvoeringsnotities.", "Demonstration schedule for {project}, covering {start} to {end}, working hours {schedule} and current progress of {progress}%.": "Demonstratieplanning voor {project}, van {start} tot {end}, werktijden {schedule} en huidige voortgang {progress}%.",
    "Planning, progress and resources by project.": "Planning, voortgang en middelen per bouwplaats.", "Assigned projects, locations and schedules.": "Toegewezen bouwplaatsen, locaties en werktijden.", "New project": "Nieuwe bouwplaats", "No projects yet": "Nog geen bouwplaatsen", "Create the first project and assign a team.": "Maak de eerste bouwplaats aan en wijs een team toe.", "The company has not assigned a project to your profile yet.": "Het bedrijf heeft nog geen bouwplaats aan jouw profiel toegewezen.", "Create project": "Bouwplaats aanmaken", "Edit project": "Bouwplaats bewerken", "Operational details and schedule": "Operationele gegevens en planning", "Delete project?": "Bouwplaats verwijderen?", "The project will be removed and assigned teams will become available. Historical attendance remains in the demo.": "De bouwplaats wordt verwijderd en toegewezen teams worden weer beschikbaar. Historische aanwezigheidsgegevens blijven in de demo behouden.", teams: "teams", people: "personen", "Project name": "Naam bouwplaats", Client: "Klant", Location: "Locatie", Description: "Beschrijving", "Start date": "Startdatum", "End date": "Einddatum", Schedule: "Werktijden", Latitude: "Breedtegraad", Longitude: "Lengtegraad", "GPS radius (50–2000 m)": "GPS-straal (50–2000 m)", complete: "voltooid", "GPS zone": "GPS-zone", "Coordinates not configured": "Coördinaten niet ingesteld", Period: "Periode", "Select to assign or remove.": "Selecteer om toe te wijzen of te verwijderen.",
    "Search, profiles, certificates and assignments.": "Zoeken, profielen, certificaten en toewijzingen.", "Name, trade, skill…": "Naam, beroep, vaardigheid…", "Clear search": "Zoekopdracht wissen", All: "Alle", results: "resultaten", "Change filters or search for another skill.": "Wijzig de filters of zoek naar een andere vaardigheid.", "Fictitious file available only to demonstrate the workflow.": "Fictief bestand alleen beschikbaar om de workflow te demonstreren.", Skills: "Vaardigheden", Assignments: "Toewijzingen", "Add to a team or project.": "Toevoegen aan een team of bouwplaats.", Trade: "Beroep", Phone: "Telefoon", Bio: "Biografie",
    "Operations Map": "Operationele kaart", "Real-time view of company sites, attendance and GPS zones.": "Realtime overzicht van bouwplaatsen, aanwezigheid en GPS-zones van het bedrijf.", "LIVE OPS": "LIVE OPERATIES", "Active sites": "Actieve bouwplaatsen", "sites monitored": "gemonitorde bouwplaatsen", "Workers on site": "Medewerkers op bouwplaats", "Open sessions": "Open sessies", "GPS validated": "GPS gevalideerd", "Inside geofence": "Binnen GPS-zone", Alerts: "Meldingen", "Outside or unverified GPS": "GPS buiten zone of niet geverifieerd", "Site network": "Bouwplaatsnetwerk", "Relative position based on configured GPS coordinates.": "Relatieve positie op basis van ingestelde GPS-coördinaten.", "on site": "op bouwplaats", Live: "Live", Alert: "Melding", Idle: "Geen sessie", "No geocoded sites": "Geen geolokaliseerde bouwplaatsen", "Set latitude and longitude on the project to include it in the operations map.": "Stel breedte- en lengtegraad van de bouwplaats in om deze op de operationele kaart te tonen.", Operating: "Operationeel", "GPS centre": "GPS-centrum", Radius: "Straal", "On site": "Op bouwplaats", "{count} session(s) require GPS attention.": "{count} sessie(s) vereisen GPS-controle.", "No active GPS violations on this site.": "Geen actieve GPS-overtredingen op deze bouwplaats.", OUT: "BUITEN", CHECK: "CONTROLEREN", "No worker has an active session on this site.": "Geen medewerker heeft een actieve sessie op deze bouwplaats.", "No sites": "Geen bouwplaatsen", "All site status": "Status van alle bouwplaatsen", "Select a site to highlight it on the map.": "Selecteer een bouwplaats om deze op de kaart te markeren.", Attention: "Aandacht",
  },
};

export function uiText(language: LanguageCode, portuguese: string, english: string) {
  if (language === "pt") return portuguese;
  if (language === "en") return english;
  return catalog[language][english] ?? english;
}

export function uiFormat(
  language: LanguageCode,
  portuguese: string,
  english: string,
  variables: Variables,
) {
  return uiText(language, portuguese, english).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match,
  );
}
